services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  HeimrichHannot\DcMultilingualUtilsBundle\:
    resource: '../../{DataContainer,EventListener,Util}'
    autoconfigure: true
    autowire: true
    public: true

  huh.dc_multilingual_utils.util.dc_multilingual_util:
    alias: 'HeimrichHannot\DcMultilingualUtilsBundle\Util\DcMultilingualUtil'
    public: true
    deprecated: "Using service alias %alias_id% is deprecated and will be removed in a feature version!"

  terminal42.dc_multilingual.querybuilder_factory:
    class: HeimrichHannot\DcMultilingualUtilsBundle\QueryBuilder\MultilingualQueryBuilderFactory
    public: true
    arguments:
      - "@database_connection"